import { IsString, IsNotEmpty } from 'class-validator';

// Data Transfer Object to verify the signature returned from our mock gateway webhooks
export class VerifyPaymentDto {
  @IsString()
  @IsNotEmpty()
  orderId: string;

  // HMAC SHA-256 signature generated by the simulated payment processor
  @IsString()
  @IsNotEmpty()
  signature: string;
}
